name: tocata_school_of_music
description: Sample styled instance App of the white label
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <3.10.1"

dependencies:
  authentication:
    path: ../../modules/authentication
  dart_melty_soundfont: 1.1.7
  design_system:
    path: ../../modules/design_system
  equatable: 2.0.5
  firebase_core: 2.15.0
  firebase_crashlytics: 3.3.4
  firebase_remote_config: 4.2.4
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_dotenv: 5.0.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: 10.1.0
  form_inputs:
    path: ../../modules/form_inputs
  formz: ^0.6.0
  get_it: 7.6.0
  intl: 0.18.0
  logger:
    path: ../../modules/logger
  shared_preferences: 2.0.15
  wl_music_school_manager:
    path: ../../modules/wl_music_school_manager

dev_dependencies:
  bloc_test: 9.1.1
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  very_good_analysis: 4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # - assets/images/
    - lib/app/environment/assets/dev/
    - lib/app/environment/assets/stg/
    - lib/app/environment/assets/prod/
